### ISSUE TITLE
still issue if no -fix-faces-fidelity supplied

### ISSUE THREAD

**Issue by Cybergate9** [brycedrennan/imaginAIry#48]
so, did a,  "pip install --upgrade imaginairy" to go up to v 2.3.0

now the following happens with no -fix-faces-fidelity supplied

> (py-venv) shaun@Shauns-MBPro14 dev % imagine "a couple smiling" --steps 40 --seed 1 --fix-faces
> 🤖🧠 imaginAIry received 1 prompt(s) and will repeat them 1 times to create 1 images.
> Loading model onto mps:0 backend...
> Generating 🖼  : "a couple smiling" 512x512px seed:1 prompt-strength:7.5 steps:40 sampler-type:plms
>     PLMS Sampler: 100%|█████████████████████████| 40/40 [00:51<00:00,  1.29s/it]
>     Fixing 😊 's in 🖼  using CodeFormer...
>     Enhancing 2 faces
> 	Failed inference for CodeFormer: '>' not supported between instances of 'NoneType' and 'int'
> 	Failed inference for CodeFormer: '>' not supported between instances of 'NoneType' and 'int'
>     🖼  [generated] saved to: ./outputs/generated/000015_1_plms40_PS7.5_a_couple_smiling_[generated].jpg
> (py-venv) shaun@Shauns-MBPro14 dev % 

adding --fix-faces-fidelity 0.2 suppresses these..

so not sure, type error in default?

**Comment by brycedrennan** [comment]
huh. thanks. I thought I addressed this but I'll take a look and see what I missed.

**Comment by Cybergate9** [comment]
Many thanks for all your work on this BTW, its a great tool to explore SD with!

**Comment by brycedrennan** [comment]
Fixed in 2.3.1

**Comment by brycedrennan** [comment]
Thanks! Still in need of quite a bit of refactoring to make it easier to understand, test, and modify.   Let me know if you're doing anything interesting with it!

**Comment by Cybergate9** [comment]
me IT prof. but complete noob to AI/ML + diffusion etc, so your tool makes it easy for someone like me who's happy on the command line, and just wants it to install and work (which it does, so you've met your goal there :-) ), so that I can explore its image creation potential to start with.. 
Your integrations of the most commonly mentioned/used 'addons' saves someone like me a heap of time, because again, they just work 'out of the box', and I can use or not use them with command line switches through your wrapper..

Eventually someone will build a 'no brainer' GUI wrapper I guess, which might be suitable for folks like me, but I can see that in your packaging that if I wanted to add more on, tinker with the Python etc. it's an easier development environment as a base..
Bit of unsolicited user feedback for you haha :-)
Have  goodly day!

**Comment by lenymo** [comment]
Can confirm that I'm still seeing this same error in 2.3.1 if I don't provide a `--fix-faces-fidelity` value. This issue did at least point in the right direction so I could see how it works.

@brycedrennan thanks for putting this library together it's great to have a powerful little command line tool which works on Apple silicon.

Also appreciate you adding the rust setup tools to the documentation. I managed to figure this out on my own prior to that being added (based on the errors I received) but it will be future for anyone trying to install this in future.

**Comment by lenymo** [comment]
Apologies @brycedrennan this appears to have been a PEBKAC issue. I have installed 2.3.1 in my local env but I must not have had my virtual environment activated so was using an old 2.2.1 version which I had previously installed globally. My bad!
